import { defineConfig } from 'astro/config'
import { unified } from '@astrojs/markdown-remark'
import UnoCSS from '@unocss/astro'
import {
  transformerNotationDiff,
  transformerNotationHighlight,
  transformerNotationWordHighlight,
} from '@shikijs/transformers'
import { remarkPlugins, siteRehypePlugins } from './src/utils/markdown-pipeline.ts'

// https://astro.build/config
export default defineConfig({
  site: 'https://teslak.me',
  output: 'static',
  trailingSlash: 'never',
  build: {
    // `file` matches `trailingSlash: 'never'` — canonical URLs and emitted
    // files agree (`/en/notes` → `en/notes.html`).
    format: 'file',
  },
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ru', 'es', 'pt', 'de', 'fr'],
    routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
    },
  },
  integrations: [
    UnoCSS({ injectReset: '@unocss/reset/tailwind.css' }),
    // The sitemap is generated by scripts/generate-seo.ts (hreflang groups,
    // draft/alias filtering, lastmod) — the generic integration cannot model
    // the fallback-alias rules, so it is intentionally not used.
  ],
  vite: {
    resolve: {
      alias: {
        '~': new URL('./src', import.meta.url).pathname,
      },
    },
  },
  markdown: {
    processor: unified({
      // The original markdown-it pipeline had no typographer; keep quotes as-is.
      smartypants: false,
      remarkPlugins: [...remarkPlugins],
      rehypePlugins: [...siteRehypePlugins],
    }),
    shikiConfig: {
      themes: {
        dark: 'vitesse-dark',
        light: 'vitesse-light',
      },
      defaultColor: false,
      cssVariablePrefix: '--s-',
      transformers: [
        transformerNotationDiff(),
        transformerNotationHighlight(),
        transformerNotationWordHighlight(),
      ],
    },
  },
})
