/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/': RouteRecordInfo<
      '/de/',
      '/de',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/[...404]': RouteRecordInfo<
      '/de/[...404]',
      '/de/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/de/articles/': RouteRecordInfo<
      '/de/articles/',
      '/de/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/articles/who-is-teslak': RouteRecordInfo<
      '/de/articles/who-is-teslak',
      '/de/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/notes': RouteRecordInfo<
      '/de/notes',
      '/de/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/now': RouteRecordInfo<
      '/de/now',
      '/de/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/photos': RouteRecordInfo<
      '/de/photos',
      '/de/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/de/projects': RouteRecordInfo<
      '/de/projects',
      '/de/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/': RouteRecordInfo<
      '/en/',
      '/en',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/[...404]': RouteRecordInfo<
      '/en/[...404]',
      '/en/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/en/articles/': RouteRecordInfo<
      '/en/articles/',
      '/en/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/articles/no-single-language': RouteRecordInfo<
      '/en/articles/no-single-language',
      '/en/no-single-language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/articles/template': RouteRecordInfo<
      '/en/articles/template',
      '/en/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/articles/who-is-teslak': RouteRecordInfo<
      '/en/articles/who-is-teslak',
      '/en/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/notes': RouteRecordInfo<
      '/en/notes',
      '/en/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/now': RouteRecordInfo<
      '/en/now',
      '/en/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/photos': RouteRecordInfo<
      '/en/photos',
      '/en/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/en/projects': RouteRecordInfo<
      '/en/projects',
      '/en/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/': RouteRecordInfo<
      '/es/',
      '/es',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/[...404]': RouteRecordInfo<
      '/es/[...404]',
      '/es/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/es/articles/': RouteRecordInfo<
      '/es/articles/',
      '/es/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/articles/no-single-language': RouteRecordInfo<
      '/es/articles/no-single-language',
      '/es/no-single-language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/articles/who-is-teslak': RouteRecordInfo<
      '/es/articles/who-is-teslak',
      '/es/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/notes': RouteRecordInfo<
      '/es/notes',
      '/es/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/now': RouteRecordInfo<
      '/es/now',
      '/es/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/photos': RouteRecordInfo<
      '/es/photos',
      '/es/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es/projects': RouteRecordInfo<
      '/es/projects',
      '/es/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/': RouteRecordInfo<
      '/fr/',
      '/fr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/[...404]': RouteRecordInfo<
      '/fr/[...404]',
      '/fr/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/fr/articles/': RouteRecordInfo<
      '/fr/articles/',
      '/fr/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/articles/who-is-teslak': RouteRecordInfo<
      '/fr/articles/who-is-teslak',
      '/fr/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/notes': RouteRecordInfo<
      '/fr/notes',
      '/fr/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/now': RouteRecordInfo<
      '/fr/now',
      '/fr/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/photos': RouteRecordInfo<
      '/fr/photos',
      '/fr/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fr/projects': RouteRecordInfo<
      '/fr/projects',
      '/fr/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/': RouteRecordInfo<
      '/pt/',
      '/pt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/[...404]': RouteRecordInfo<
      '/pt/[...404]',
      '/pt/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/pt/articles/': RouteRecordInfo<
      '/pt/articles/',
      '/pt/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/articles/no-single-language': RouteRecordInfo<
      '/pt/articles/no-single-language',
      '/pt/no-single-language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/articles/who-is-teslak': RouteRecordInfo<
      '/pt/articles/who-is-teslak',
      '/pt/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/notes': RouteRecordInfo<
      '/pt/notes',
      '/pt/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/now': RouteRecordInfo<
      '/pt/now',
      '/pt/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/photos': RouteRecordInfo<
      '/pt/photos',
      '/pt/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pt/projects': RouteRecordInfo<
      '/pt/projects',
      '/pt/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/': RouteRecordInfo<
      '/ru/',
      '/ru',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/[...404]': RouteRecordInfo<
      '/ru/[...404]',
      '/ru/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/ru/articles/': RouteRecordInfo<
      '/ru/articles/',
      '/ru/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/articles/[...404]': RouteRecordInfo<
      '/ru/articles/[...404]',
      '/ru/articles/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/ru/articles/colophon': RouteRecordInfo<
      '/ru/articles/colophon',
      '/ru/colophon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/articles/no-single-language': RouteRecordInfo<
      '/ru/articles/no-single-language',
      '/ru/no-single-language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/articles/robophobia': RouteRecordInfo<
      '/ru/articles/robophobia',
      '/ru/robophobia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/articles/who-is-teslak': RouteRecordInfo<
      '/ru/articles/who-is-teslak',
      '/ru/who-is-teslak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/notes': RouteRecordInfo<
      '/ru/notes',
      '/ru/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/now': RouteRecordInfo<
      '/ru/now',
      '/ru/now',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/photos': RouteRecordInfo<
      '/ru/photos',
      '/ru/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ru/projects': RouteRecordInfo<
      '/ru/projects',
      '/ru/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/index.md': {
      routes:
        | '/de/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/[...404].md': {
      routes:
        | '/de/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/de/articles/index.md': {
      routes:
        | '/de/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/articles/who-is-teslak.md': {
      routes:
        | '/de/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/notes.md': {
      routes:
        | '/de/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/now.md': {
      routes:
        | '/de/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/photos.md': {
      routes:
        | '/de/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/de/projects.md': {
      routes:
        | '/de/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/index.md': {
      routes:
        | '/en/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/[...404].md': {
      routes:
        | '/en/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/en/articles/index.md': {
      routes:
        | '/en/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/articles/no-single-language.md': {
      routes:
        | '/en/articles/no-single-language'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/articles/template.md': {
      routes:
        | '/en/articles/template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/articles/who-is-teslak.md': {
      routes:
        | '/en/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/notes.md': {
      routes:
        | '/en/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/now.md': {
      routes:
        | '/en/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/photos.md': {
      routes:
        | '/en/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/en/projects.md': {
      routes:
        | '/en/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/index.md': {
      routes:
        | '/es/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/[...404].md': {
      routes:
        | '/es/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/es/articles/index.md': {
      routes:
        | '/es/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/articles/no-single-language.md': {
      routes:
        | '/es/articles/no-single-language'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/articles/who-is-teslak.md': {
      routes:
        | '/es/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/notes.md': {
      routes:
        | '/es/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/now.md': {
      routes:
        | '/es/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/photos.md': {
      routes:
        | '/es/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/es/projects.md': {
      routes:
        | '/es/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/index.md': {
      routes:
        | '/fr/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/[...404].md': {
      routes:
        | '/fr/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/fr/articles/index.md': {
      routes:
        | '/fr/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/articles/who-is-teslak.md': {
      routes:
        | '/fr/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/notes.md': {
      routes:
        | '/fr/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/now.md': {
      routes:
        | '/fr/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/photos.md': {
      routes:
        | '/fr/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/fr/projects.md': {
      routes:
        | '/fr/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/index.md': {
      routes:
        | '/pt/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/[...404].md': {
      routes:
        | '/pt/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/pt/articles/index.md': {
      routes:
        | '/pt/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/articles/no-single-language.md': {
      routes:
        | '/pt/articles/no-single-language'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/articles/who-is-teslak.md': {
      routes:
        | '/pt/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/notes.md': {
      routes:
        | '/pt/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/now.md': {
      routes:
        | '/pt/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/photos.md': {
      routes:
        | '/pt/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/pt/projects.md': {
      routes:
        | '/pt/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/index.md': {
      routes:
        | '/ru/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/[...404].md': {
      routes:
        | '/ru/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/ru/articles/index.md': {
      routes:
        | '/ru/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/articles/[...404].md': {
      routes:
        | '/ru/articles/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/ru/articles/colophon.md': {
      routes:
        | '/ru/articles/colophon'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/articles/no-single-language.md': {
      routes:
        | '/ru/articles/no-single-language'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/articles/robophobia.md': {
      routes:
        | '/ru/articles/robophobia'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/articles/who-is-teslak.md': {
      routes:
        | '/ru/articles/who-is-teslak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/notes.md': {
      routes:
        | '/ru/notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/now.md': {
      routes:
        | '/ru/now'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/photos.md': {
      routes:
        | '/ru/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ru/projects.md': {
      routes:
        | '/ru/projects'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
